name: Notify Telegram

on:
  push:
    branches:
      - master  # Notifica commits ou pushes na branch "master"
  pull_request:
    types: [opened, closed]

jobs:
  notify-telegram:
    runs-on: ubuntu-24.04

    steps:
      - name: Enviar notificaÃ§Ã£o para o Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            MESSAGE="ğŸ“¦ *New Push on Repository*\n\nğŸ”§ Repository: ${{ github.repository }}\nğŸ‘¤ Actor: ${{ github.actor }}\nğŸ“ Message Commit:\n$(git log -1 --pretty=%B)"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            MESSAGE="ğŸ“Œ *Pull Request ${ACTION}:*\n\nğŸ”§ Repository: ${{ github.repository }}\nğŸ‘¤ Actor: ${{ github.actor }}\nğŸ“ Title: ${PR_TITLE}\nğŸ”— [View PR](${PR_URL})"
          fi

          curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MESSAGE\", \"parse_mode\": \"Markdown\"}"
